export const DATA = [
  {
    id: 1,
    title: "Lucky Crypto",
    price: "30 000€",
    tokenPrice: "30€",
    picture: require("../../assets/images/horse1.png"),
    deadline: "Finit dans 30 jours",
  },
  {
    id: 2,
    title: "Millenium",
    price: "40 000€",
    tokenPrice: "40€",
    picture: require("../../assets/images/horse2.png"),
    deadline: "Finit dans 4 jours",
  },
  {
    id: 3,
    title: "Alyra du web",
    price: "20 000€",
    tokenPrice: "20€",
    picture: require("../../assets/images/horse3.jpg"),
    deadline: "Finit dans 15 jours",
  },
  {
    id: 4,
    title: "Klodette de Massa",
    price: "35 000€",
    tokenPrice: "35€",
    picture: require("../../assets/images/horse4.png"),
    deadline: "Finit dans 1 heure",
  },
  {
    id: 5,
    title: "Klodette de Massa",
    price: "27 000€",
    tokenPrice: "27€",
    picture: require("../../assets/images/horse3.jpg"),
    deadline: "",
  },
  {
    id: 6,
    title: "Klodette de Massa",
    price: "27 000€",
    tokenPrice: "27€",
    picture: require("../../assets/images/horse3.jpg"),
    deadline: "",
  },
  {
    id: 7,
    title: "Klodette de Massa",
    price: "27 000€",
    tokenPrice: "27€",
    picture: require("../../assets/images/horse3.jpg"),
    deadline: "",
  },
  {
    id: 8,
    title: "Klodette de Massa",
    price: "27 000€",
    tokenPrice: "27€",
    picture: require("../../assets/images/horse3.jpg"),
    deadline: "",
  },
]
